### ISSUE TITLE
Rust-Dart Async FFI

### ISSUE THREAD

**Issue by goozang-records** [sunshine-protocol/sunshine-bounty-ui#11]
https://michael-f-bryan.github.io/rust-ffi-guide/async.html

How do we express async task scheduling between Rust and Dart FFI? Dart has a runtime executor, but Rust does not.

The naive solution would be to wrap every async call as `block_on(task)` so we spawn a thread for every task...

cc @shekohex @dvc94ch

**Comment by shekohex** [comment]
the current work is happing on [flutterust](https://github.com/shekohex/flutterust) to get the Async Rust to Work Async Dart :)

**Comment by shekohex** [comment]
I'm going to close this since we already solved how to handle async Rust and async Dart
